# Generated by Django 3.2.16 on 2022-12-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
